### ISSUE TITLE
something wrong with `computeLikelihoodSum`

### ISSUE THREAD

**Issue by chad3814** [chad3814/elo-mmr#1]
https://github.com/chad3814/elo-mmr/blob/f198dd1c21affc667c84b5230b29644fe8174d50/lib/compute_likelihood_sum.ts#L18
@duhby, I don't suppose you could look at this and your python function https://github.com/duhby/elommr/blob/c8b3431721f698e20e4c72d496648d1dbd41798c/elommr/elommr.py#L477 and tell me what I'm doing wrong?

**Comment by chad3814** [comment]
I'm not great at python, and I'm not smart enough to understand the paper, but I was able to get the majority ported to typescript, but I'm not getting the right ratings after updating rounds.

**Comment by duhby** [comment]
https://github.com/chad3814/elo-mmr/blob/1c19e30ced3cdd74bff20e11e63a057c0e68ba7f/lib/elo_mmr.ts#L39
Should be `this.mult = (splitTies ? 1 : 2);`
https://github.com/chad3814/elo-mmr/blob/1c19e30ced3cdd74bff20e11e63a057c0e68ba7f/lib/player.ts#L72
Should be `-this.normalFactor.mu * weightNormal,`

**Comment by chad3814** [comment]
I found the `splitTies` issue yesterday, but that negation in player was key! Thank you so much!
